
apiVersion: v1
kind: Service
metadata:
  name: shiptrackr-locust
spec:
  selector:
    app: shiptrackr-locust
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer
