
apiVersion: v1
kind: Secret
metadata:
  name: shiptrackr-secrets
  namespace: default
  labels:
    app: shiptrackr
    environment: production
  annotations:
    description: Base secrets for ShipTrackr API and database
    managed-by: helm
    created-by: shiptrackr-setup
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9zaGlwdHJhY2tyX3VzZXI6cGFzc3dvcmRAMTI3LjAuMC4xOjU0MzIvY2xpZW50X2Ri
  JWT_SECRET: c3VwZXJzZWN1cmVqd3RzZWNyZXQ=
  PORT:MzAwMA==
